# Generated by Django 3.0.5 on 2020-05-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_datatime',
            field=models.DateTimeField(),
        ),
    ]
